# This is a basic workflow that is manually triggered

name: Install surfboard

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install waves/surfboard
        run: npm install -g @waves/surfboard
      - name: deploy babyduck breeding
        run: surfboard run deploy-scripts/dapp.deploy.js
        env:
          FILE: babyDuckBreeding
          SEED: ${{ secrets.BABYDUCKBREEDINGSEED }}
